"""Generate a tiny synthetic stand-in dataset so the pipeline runs today.

    python scripts/make_synthetic_demo.py

============================== READ THIS FIRST ==============================
This is a SMOKE TEST, not a corpus, and nothing measured on it may be reported
as a result. Its only job is to prove that the manifest builder, the audio
front end and the QC pass work end to end while ASVspoof 2019 LA, ASVspoof
2021 DF and WaveFake are still downloading. Every file it writes is a
mathematical construction; no human ever spoke any of it, and no real
text-to-speech system produced any of it. A classifier will separate these two
classes almost perfectly, which tells us nothing except that the code runs.
=============================================================================

What it produces
----------------
* ``data/synthetic_demo/flac/LA_T_*.flac`` - 120 files, 8 pseudo-speakers,
  ~2 s each at 16 kHz, FLAC, exactly as ASVspoof 2019 LA ships.
* ``data/synthetic_demo/protocol.txt`` - a protocol in ASVspoof 2019 LA
  format, so it is parsed by the *real* parser in :mod:`src.manifest` rather
  than by a shortcut written for the demo.
* ``data/synthetic_demo/README.txt`` - the same warning, next to the data.

How the two classes are made to differ
--------------------------------------
Both classes come from the same source-filter model: a harmonic voice source
shaped by a speaker-specific formant envelope, gated by a syllable-rate energy
envelope. The "spoof" class then receives two alterations chosen because real
neural vocoders show them:

1. **Band limitation above ~7 kHz.** Vocoders reconstruct a waveform from a
   mel-spectrogram, whose upper mel bands are wide and sparsely resolved, so
   the top of the band is reproduced poorly. An 8th-order Butterworth low-pass
   stands in for that. This is the artefact LFCC is expected to see and MFCC is
   expected to miss, because the mel scale spends few filters up there - which
   is precisely the comparison the project is built around.

2. **Over-regular harmonic phase and no jitter.** Real phonation is slightly
   irregular: the fundamental wanders (jitter), harmonic amplitudes fluctuate
   (shimmer), and the phase relationship between harmonics is not fixed. A
   vocoder that reconstructs phase from a magnitude spectrogram tends to
   produce a signal that is *too* regular. The spoof class therefore gets zero
   jitter, zero shimmer, and a fixed phase for every harmonic.

Both classes get the same distribution of leading/trailing silence, on purpose.
Making silence a cue here would bake in exactly the ASVspoof shortcut that
:func:`src.audio.trim_silence` warns about, and the demo would then reward a
detector for the wrong reason.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy import signal
from tqdm import tqdm

# Make `src` importable when the script is run directly from anywhere.
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.config import load_config, new_rng, set_seed  # noqa: E402

WARNING_BANNER = """\
SYNTHETIC SMOKE-TEST DATA - NOT A CORPUS, NOT RESULTS.

Generated by scripts/make_synthetic_demo.py for the sole purpose of exercising
the Phase 1 pipeline (manifest -> QC -> tests) before the real corpora finish
downloading. The "bonafide" files were not spoken by a human and the "spoof"
files were not produced by a text-to-speech or voice-conversion system: both
are additive-synthesis constructions that differ by a deliberate 7 kHz
low-pass and a deliberate lack of phase/pitch irregularity.

Any accuracy, EER or ROC-AUC computed on this data is a pipeline check.
It must never appear in the report as an experimental result.
"""


def speaker_profile(speaker_index: int) -> dict[str, float | list[float]]:
    """Derive a fixed, reproducible "voice" from a speaker index.

    Deterministic rather than random, so speaker 3 is the same voice on every
    machine and every run - which is what makes the speaker-disjoint split test
    meaningful.

    Args:
        speaker_index: 0-based speaker number.

    Returns:
        Fundamental frequency and three formant centre frequencies/bandwidths,
        spread over a plausible adult range.
    """
    # f0 from 105 Hz (low male) up to ~230 Hz (high female) across 8 speakers.
    f0 = 105.0 + 18.0 * speaker_index
    # Formants shift with vocal-tract length, which correlates with f0; the
    # scale factor keeps higher-pitched speakers' formants higher.
    scale = 1.0 + 0.05 * (speaker_index - 3.5)
    return {
        "f0": f0,
        "formants": [700.0 * scale, 1220.0 * scale, 2600.0 * scale],
        "bandwidths": [90.0, 110.0, 170.0],
    }


def formant_envelope(
    frequencies: np.ndarray, formants: list[float], bandwidths: list[float]
) -> np.ndarray:
    """Amplitude gain at each frequency from a sum of resonances.

    Each formant is modelled as a Lorentzian peak

    .. math:: G_i(f) = \\frac{1}{1 + \\left(\\frac{f - F_i}{B_i / 2}\\right)^2}

    which is the magnitude response of a simple second-order resonator near its
    peak. Summing three of them and adding the -6 dB/octave source tilt gives a
    spectral envelope that looks like a vowel.

    Args:
        frequencies: Frequencies to evaluate, in Hz.
        formants: Formant centre frequencies, in Hz.
        bandwidths: Corresponding -3 dB bandwidths, in Hz.

    Returns:
        Gain at each frequency, normalised to a maximum of 1.
    """
    gain = np.zeros_like(frequencies, dtype=np.float64)
    for centre, bandwidth in zip(formants, bandwidths):
        gain += 1.0 / (1.0 + ((frequencies - centre) / (bandwidth / 2.0)) ** 2)

    # Glottal source rolls off at roughly -6 dB/octave above ~100 Hz.
    tilt = 1.0 / (1.0 + (np.maximum(frequencies, 1.0) / 100.0))
    gain = gain * tilt
    peak = float(gain.max())
    return gain / peak if peak > 0 else gain


def syllable_envelope(
    n_samples: int, sample_rate: int, rng: np.random.Generator
) -> np.ndarray:
    """A speech-like amplitude envelope: a few syllables inside silent margins.

    Syllable rate is drawn near 4 Hz, which is where real speech sits. The
    silent head and tail are drawn from the *same* distribution regardless of
    class - see the module docstring for why that matters.

    Args:
        n_samples: Length of the envelope.
        sample_rate: Sample rate in Hz.
        rng: Seeded generator.

    Returns:
        A non-negative envelope of length ``n_samples``.
    """
    time = np.arange(n_samples) / sample_rate
    duration = n_samples / sample_rate

    syllable_rate = float(rng.uniform(3.0, 5.0))
    phase = float(rng.uniform(0, 2 * np.pi))
    # Raised cosine at the syllable rate, never quite reaching zero, so voiced
    # regions stay connected the way they do in continuous speech.
    envelope = 0.55 + 0.45 * np.cos(2 * np.pi * syllable_rate * time + phase)

    # Silent margins: 100-350 ms at each end, class-independent by design.
    head = float(rng.uniform(0.10, 0.35))
    tail = float(rng.uniform(0.10, 0.35))
    gate = np.ones(n_samples)
    gate[time < head] = 0.0
    gate[time > (duration - tail)] = 0.0

    # 20 ms raised-cosine fades, so the gate does not produce a click (a click
    # is broadband and would swamp the 7 kHz cue we are trying to plant).
    fade_len = max(1, int(0.02 * sample_rate))
    fade = 0.5 * (1 - np.cos(np.linspace(0, np.pi, fade_len)))
    gate = np.convolve(gate, fade / fade.sum(), mode="same")

    return envelope * gate


def synthesize(
    is_spoof: bool,
    profile: dict,
    duration: float,
    sample_rate: int,
    lowpass_hz: float,
    rng: np.random.Generator,
) -> np.ndarray:
    """Synthesise one utterance of the requested class.

    Args:
        is_spoof: Produce the "AI-generated" class if True.
        profile: Output of :func:`speaker_profile`.
        duration: Length in seconds.
        sample_rate: Sample rate in Hz.
        lowpass_hz: Cutoff of the vocoder-like low-pass applied to spoof files.
        rng: Seeded generator.

    Returns:
        A 1-D float32 waveform, peak-scaled to a level well below full scale.
    """
    n_samples = int(round(duration * sample_rate))
    time = np.arange(n_samples) / sample_rate
    nyquist = sample_rate / 2.0

    base_f0 = float(profile["f0"])

    # --- pitch contour -----------------------------------------------------
    # A slow declination plus a gentle intonation sweep, shared by both classes.
    contour = base_f0 * (1.0 - 0.08 * time / max(duration, 1e-9))
    contour = contour * (1.0 + 0.04 * np.sin(2 * np.pi * 0.7 * time))

    if not is_spoof:
        # Jitter: a smoothed random walk of about 1% - the cycle-to-cycle pitch
        # irregularity that real phonation always has and vocoders smooth away.
        walk = rng.normal(0.0, 1.0, n_samples).cumsum()
        walk = walk / (np.abs(walk).max() + 1e-9)
        contour = contour * (1.0 + 0.012 * walk)

    # Instantaneous phase of the fundamental: integrating the frequency contour
    # is what lets the pitch actually move.
    phase_f0 = 2 * np.pi * np.cumsum(contour) / sample_rate

    # --- harmonic source ---------------------------------------------------
    n_harmonics = int(nyquist // base_f0)
    harmonic_numbers = np.arange(1, n_harmonics + 1)
    mean_frequencies = base_f0 * harmonic_numbers
    gains = formant_envelope(
        mean_frequencies, list(profile["formants"]), list(profile["bandwidths"])
    )

    if is_spoof:
        # Over-regular: every harmonic locked to the same phase origin, and no
        # amplitude fluctuation. This is the phase artefact of a vocoder that
        # reconstructs from magnitude only.
        harmonic_phases = np.zeros(n_harmonics)
        shimmer = np.ones(n_harmonics)
    else:
        harmonic_phases = rng.uniform(0, 2 * np.pi, n_harmonics)
        shimmer = 1.0 + rng.normal(0.0, 0.08, n_harmonics)

    waveform = np.zeros(n_samples, dtype=np.float64)
    for index, harmonic in enumerate(harmonic_numbers):
        if mean_frequencies[index] >= nyquist:
            break  # never synthesise above Nyquist: that would alias
        waveform += (
            gains[index]
            * shimmer[index]
            * np.sin(harmonic * phase_f0 + harmonic_phases[index])
        )

    # --- aspiration noise --------------------------------------------------
    # Real voices carry breath noise; over-smooth vocoder output carries less.
    noise_gain = 0.010 if is_spoof else 0.035
    waveform += noise_gain * rng.normal(0.0, 1.0, n_samples)

    # --- envelope ----------------------------------------------------------
    waveform *= syllable_envelope(n_samples, sample_rate, rng)

    # --- the vocoder-like band limitation ----------------------------------
    if is_spoof:
        sos = signal.butter(
            8, lowpass_hz / nyquist, btype="lowpass", output="sos"
        )
        # filtfilt: zero phase distortion, so the low-pass changes the
        # magnitude spectrum only and the phase cue stays independent of it.
        waveform = signal.sosfiltfilt(sos, waveform)

    # --- level -------------------------------------------------------------
    # Target a random peak in [0.25, 0.65] rather than normalising to 1.0, so
    # the QC level histogram has something to show and nothing is clipped.
    peak = float(np.max(np.abs(waveform)))
    if peak > 0:
        waveform = waveform * (float(rng.uniform(0.25, 0.65)) / peak)

    return waveform.astype(np.float32)


def main() -> int:
    """Write the synthetic dataset and its ASVspoof-format protocol."""
    cfg = load_config()
    set_seed(cfg.seed)

    synthetic_cfg = cfg.synthetic
    n_speakers = int(synthetic_cfg.n_speakers)
    n_per_speaker = int(synthetic_cfg.n_utts_per_speaker)
    sample_rate = int(synthetic_cfg.sample_rate)
    mean_duration = float(synthetic_cfg.duration)
    jitter = float(synthetic_cfg.duration_jitter)
    spoof_fraction = float(synthetic_cfg.spoof_fraction)
    attacks = list(synthetic_cfg.attacks)
    lowpass_hz = float(synthetic_cfg.lowpass_hz)

    root = cfg.path("synthetic")
    audio_dir = root / "flac"
    audio_dir.mkdir(parents=True, exist_ok=True)

    rng = new_rng(int(cfg.seed))
    protocol_lines: list[str] = []
    total = n_speakers * n_per_speaker

    print("=" * 72)
    print("Generating SYNTHETIC SMOKE-TEST data - not a corpus, not results.")
    print(f"  {total} files, {n_speakers} pseudo-speakers, {sample_rate} Hz FLAC")
    print(f"  spoof cue: {lowpass_hz:.0f} Hz low-pass + fixed harmonic phase")
    print("=" * 72)

    utterance_number = 0
    spoof_counter = 0
    for speaker_index in tqdm(range(n_speakers), desc="speakers", unit="spk"):
        profile = speaker_profile(speaker_index)
        speaker_id = f"LA_{speaker_index:04d}"

        # Interleave the classes within each speaker so that both classes are
        # present for every voice. A speaker-disjoint split then moves whole
        # voices across without disturbing the class balance.
        n_spoof_per_speaker = int(round(n_per_speaker * spoof_fraction))
        spoof_flags = np.zeros(n_per_speaker, dtype=bool)
        if n_spoof_per_speaker > 0:
            positions = np.linspace(0, n_per_speaker - 1, n_spoof_per_speaker)
            spoof_flags[np.round(positions).astype(int)] = True

        for utterance_index in range(n_per_speaker):
            utterance_number += 1
            utt_id = f"LA_T_{utterance_number:07d}"
            is_spoof = bool(spoof_flags[utterance_index])

            duration = float(
                np.clip(rng.normal(mean_duration, jitter / 2.0),
                        mean_duration - jitter, mean_duration + jitter)
            )
            waveform = synthesize(
                is_spoof=is_spoof,
                profile=profile,
                duration=duration,
                sample_rate=sample_rate,
                lowpass_hz=lowpass_hz,
                rng=rng,
            )

            sf.write(
                audio_dir / f"{utt_id}.flac",
                waveform,
                sample_rate,
                format="FLAC",
                subtype="PCM_16",   # FLAC is integer-only; 16 bit matches ASVspoof
            )

            if is_spoof:
                # Cycle through the pseudo-attack ids so both appear for every
                # speaker; the column layout matches 2019 LA exactly.
                attack = attacks[spoof_counter % len(attacks)]
                spoof_counter += 1
                protocol_lines.append(f"{speaker_id} {utt_id} - {attack} spoof")
            else:
                protocol_lines.append(f"{speaker_id} {utt_id} - - bonafide")

    protocol_path = root / "protocol.txt"
    protocol_path.write_text("\n".join(protocol_lines) + "\n", encoding="utf-8")
    (root / "README.txt").write_text(WARNING_BANNER, encoding="utf-8")

    n_spoof = sum(1 for line in protocol_lines if line.endswith("spoof"))
    print()
    print(f"Wrote {total} FLAC files to {audio_dir}")
    print(f"Wrote protocol           {protocol_path}")
    print(f"Class balance            {total - n_spoof} bonafide / {n_spoof} spoof")
    print(f"Speakers                 {n_speakers} (LA_0000 .. LA_{n_speakers - 1:04d})")
    print()
    print("Next: python scripts/01_build_manifest.py --synthetic")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
